name: BuildAndDeploy

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          npm install
          npm install -g gatsby-cli
      
      - name: Build
        run: gatsby build
      
      - name: Deploy
        env:
          LOCAL_BUILD_DIRECTORY: public
          DEPLOY_DIRECTORY_NAME: ${{ secrets.DEPLOY_DIR }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          
        run: |
          mkdir -p "$HOME/.ssh"
          echo "$DEPLOY_KEY" >"$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"
          rsync -avz --delete -e 'ssh -i $HOME/.ssh/key' ${LOCAL_BUILD_DIRECTORY} {DEPLOY_USER}@{DEPLOY_HOST}:${DEPLOY_DIRECTORY_NAME}
          rm "$HOME/.ssh/key"
