name: BuildAndDeploy

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          npm install
          npm install -g gatsby-cli
      
      - name: Build
        run: gatsby build
      
      - name: Setup SSH
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_KEY" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
      
      - name: Deploy
        env:
          LOCAL_BUILD_DIRECTORY: public
          DEPLOY_DIRECTORY_NAME: ${{ secrets.DEPLOY_DIR }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: rsync -avz --delete -e 'ssh -i ~/.ssh/deploy.key -o StrictHostKeyChecking=no' ${LOCAL_BUILD_DIRECTORY} ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY_NAME}
